import {
  DT,
  DRIVER_NOISE,
  FLEET_CEILING,
  JAM_GAP,
  NARROW_SCREEN_SHARE,
  TRAFFIC_DENSITY,
} from '../params';
import type { SimWorld } from '../world';
import { ARCHETYPES, type Archetype, archetypeWeights } from './archetypes';
import { makeDriver } from './driver';
import { createVehicle, snapshot } from './state';
import { planFrom } from '../routing/router';
import { assignOccupancy } from './kerbStops';

/**
 * Arrival rate at one boundary entry lane, vehicles per second, at traffic
 * intensity and demand 1 (about 180 an hour a lane, a quiet city street).
 */
export const ENTRY_RATE = 0.05;
/** Vehicles an entry holds outside the map before further arrivals are lost. */
export const ENTRY_QUEUE = 6;
/** Most vehicles admitted onto the map in one tick, city-wide. */
const ADMIT_PER_TICK = 4;

/**
 * Density ceiling on the fleet, from total road length.
 *
 * Traffic is generated by demand at each entry (`stepDispatch`); this only
 * stops a saturated map from growing without bound, which would cost frame
 * rate without adding anything a player could see. `FLEET_CEILING` is a
 * runaway guard far above it.
 */
export function trafficTarget(w: SimWorld): number {
  let total = 0;
  for (const ribbon of w.net.ribbons.values()) total += ribbon.full.length;
  const narrow = typeof window !== 'undefined' && window.innerWidth < 800;
  const ceiling = narrow ? Math.floor(FLEET_CEILING * NARROW_SCREEN_SHARE) : FLEET_CEILING;
  return Math.min(
    ceiling,
    Math.floor(total * TRAFFIC_DENSITY * w.trafficIntensity * w.demandMultiplier),
  );
}

/** Lane entries at the edge of the map, where traffic arrives from outside. */
function entryLanes(w: SimWorld): string[] {
  const out: string[] = [];
  for (const lane of w.graph.lanelets.values()) {
    if (lane.kind !== 'link' || lane.length < 30) continue;
    if (w.rt(lane.id).ghost) continue;
    if (lane.from !== undefined && w.doc.degree(lane.from) === 1) out.push(lane.id);
  }
  return out.sort();
}

/** Seconds to the next arrival of a Poisson stream of `rate` per second. */
function nextGap(w: SimWorld, rate: number): number {
  return -Math.log(1 - w.rng.spawnVehicles.float()) / Math.max(rate, 1e-9);
}

/**
 * Brings traffic in at the edges of the map.
 *
 * This used to be ONE attempt every half second for the whole city, placed at
 * whichever entry was least occupied: however many roads led into the map,
 * no more than two vehicles a second could arrive, and the traffic went
 * wherever the map was emptiest rather than where it was coming from. Every
 * boundary entry lane now has its own arrival stream. An arrival that finds
 * its entry full waits outside the map rather than vanishing, up to
 * `ENTRY_QUEUE` vehicles; when there is room, the arrivals that have waited
 * longest anywhere in the city come in first.
 */
export function stepDispatch(w: SimWorld, enabled: boolean): void {
  if (!enabled) return;
  w.vehicleSpawnClock += DT;
  const now = w.vehicleSpawnClock;
  const rate = ENTRY_RATE * w.trafficIntensity * w.demandMultiplier;
  const entries = entryLanes(w);

  const live = new Set(entries);
  for (const id of [...w.entryDemand.keys()]) if (!live.has(id)) w.entryDemand.delete(id);

  for (const id of entries) {
    let demand = w.entryDemand.get(id);
    if (!demand) {
      demand = { next: now + nextGap(w, rate), waiting: [] };
      w.entryDemand.set(id, demand);
    }
    if (rate <= 0) continue;
    while (demand.next <= now) {
      if (demand.waiting.length < ENTRY_QUEUE) demand.waiting.push(demand.next);
      else w.entryDemandLost++;
      demand.next += nextGap(w, rate);
    }
  }

  const cap = trafficTarget(w);
  const blocked = new Set<string>();
  for (let admitted = 0; admitted < ADMIT_PER_TICK && w.vehicles.size < cap; admitted++) {
    // Oldest waiting arrival first, anywhere on the map; ties by lane id.
    let best: string | null = null;
    let bestAt = Infinity;
    for (const id of entries) {
      if (blocked.has(id)) continue;
      const at = w.entryDemand.get(id)?.waiting[0];
      if (at !== undefined && at < bestAt) {
        best = id;
        bestAt = at;
      }
    }
    if (best === null) break;
    if (spawnAt(w, best)) w.entryDemand.get(best)?.waiting.shift();
    else blocked.add(best);
  }
}

/**
 * Spawns one vehicle at the first entry lane with room for it. Kept for
 * harnesses that place traffic directly; the running game uses
 * `stepDispatch`.
 */
export function spawnVehicle(w: SimWorld): boolean {
  for (const id of entryLanes(w)) if (spawnAt(w, id)) return true;
  return false;
}

/**
 * Puts one vehicle on the map at the start of an entry lane, if the lane has
 * room behind whatever is already on it.
 *
 * Only ever at an edge of the map: materialising a car halfway along a street
 * is both visually jarring and physically false, so a closed network with no
 * boundary entry receives no traffic until the player connects one.
 */
function spawnAt(w: SimWorld, id: string): boolean {
  const lane = w.lanelet(id);
  if (!lane) return false;
  const arch = w.rng.spawnVehicles.weighted(archetypeWeights()) as Archetype;
  // The tail includes a body still sliding out of this lane.
  let tailRear = Infinity;
  for (const body of w.bodiesIn(id)) tailRear = Math.min(tailRear, body.s - body.vehicle.archetype.length);
  const entryClearance = Math.max(0.5, Math.min(1.5, arch.width / 4));
  // `s` is the front of the vehicle. Its rear must be on the authored road
  // at birth; the entry node has no lanelet behind it to carry the body.
  if (lane.length <= arch.length + entryClearance) return false;
  if (tailRear < arch.length + entryClearance + JAM_GAP) return false;

  // The driver is drawn BEFORE the free-flow speed and from the same stream,
  // so the two are part of one personality rather than two independent rolls.
  const driver = makeDriver(arch, () => w.rng.driver.float());
  const v0 =
    lane.speedLimit *
    arch.speedFactor *
    w.rng.driver.range(DRIVER_NOISE.lo, DRIVER_NOISE.hi) *
    // A pushy driver wants more than the limit and a timid one less, on top
    // of the ordinary spread. Without it every driver in the fleet converges
    // on the same cruise and the only thing distinguishing them is how they
    // got there.
    (1 + driver.aggression * 0.07);

  const palette = arch.palette;
  const color = palette[Math.floor(w.rng.spawnVehicles.float() * palette.length)] as string;

  const vehicle = createVehicle(w.nextVehicleId++, arch, driver, color, id, v0, w.clock.tick);
  vehicle.s = arch.length + entryClearance;
  vehicle.v = Math.min(v0 * 0.4, lane.speedLimit * 0.4);
  vehicle.prev = snapshot(vehicle);

  assignOccupancy(w, vehicle);

  w.vehicles.set(vehicle.id, vehicle);
  w.enterLanelet(vehicle, id);
  planFrom(w, vehicle);
  return true;
}

/** Removes vehicles that have reached a dead end and stopped there. */
export function stepDespawn(w: SimWorld): void {
  for (const v of w.vehiclesInIdOrder()) {
    const lane = w.lanelet(v.lanelet);
    if (!lane) {
      w.removeVehicle(v);
      continue;
    }
    // The end-of-route obstacle brings a vehicle to rest at its standstill gap,
    // not against the very end of the lane, so the despawn threshold has to
    // allow for that — otherwise cars park just short of a map edge forever and
    // slowly plug the exit stub.
    const atEnd = lane.length - v.s < v.driver.s0 + 2;
    const nowhereToGo = w.graph.exitsOf(v.lanelet).length === 0;
    if (lane.kind === 'link' && atEnd && nowhereToGo) {
      w.removeVehicle(v);
    }
  }
}

export { ARCHETYPES };
